name: revfood
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-339.0.dev <4.0.0"

dependencies:
  app_settings: ^4.2.0
  cloud_firestore: ^4.7.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.11
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  google_sign_in: ^6.1.3
  image_picker: ^0.8.9
  lottie: ^2.3.2
  twitter_login: ^4.0.1
dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets\images\Revfood_logo_red_script_resized.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Revfood_logo_red.png"

flutter:
  fonts:
    - family: lol
      fonts:
        - asset: assets\fonts\lol.ttf
    - family: poppins
      fonts:
        - asset: assets\fonts\Poppins-Medium.ttf
    - family: bigpoppins
      fonts:
        - asset: assets\fonts\Poppins-Black.ttf
    - family: rubik
      fonts:
        - asset: assets\fonts\Rubik-Italic-VariableFont_wght.ttf

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets\animation\hello.json
    - assets\animation\login_animation.json
    - assets\animation\loc_ay.json
    - assets\animation\discover.json
    - assets\animation\review.json
    - assets\animation\welcome.json
    - assets\animation\nearby.json
    - assets\animation\empty.json
    - assets\images\Revfood_logo_red_script.png
    - assets\images\Revfood_logo_red_script_resized.png
    - assets\images\Revfood_logo_red.png
    - assets\images\Revfood_logo_red_resized.png
    - assets\images\Revfood_logo_white.png
    - assets\images\Revfood_logo_black.png
    - assets\animation\Location.json
    - assets\images\profil_background.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
